clear all

global Slider_Ifr Text_Ifr Slider_PBS Text_PBS ...
        dat  FP cgdat VPause ...
        VSliderPBS Ifr PBS fr az el IRep F
    
    
[File,Path]=uigetfile('results');
load([Path File]);

%視点　
az = 90; el = 0;   %被験者の右側から

dat = dat';
Ifr = 1;    %始めは1フレームからスタート
PBS = 0.1;
VPause = 1;
IRep = 1;

Fig = figure('Name','Stick Picture',...
             'NumberTitle','off','Position',[500,50,800,900]);
%Start Button
PBSart = uicontrol(gcf,'Style','Pushbutton','Position',[20,50,100,80],...
                       'String','⇒','FontSize',40,'Callback',...
                       'StickPicture(''Start'')');
%Pause Button
PBPause = uicontrol(gcf,'Style','Pushbutton','Position',[140,50,100,80],...
                       'String','■','FontSize',20,'Callback',...
                       'StickPicture(''Pause'')');
%Exit Button
PBExit = uicontrol(gcf,'Style','Pushbutton','Position',[260,50,100,80],...
                       'String','Exit','FontSize',20,'Callback',...
                       'StickPicture(''Exit'')');

%Rec Button
PBRec = uicontrol(gcf,'Style','Pushbutton','Position',[380,50,100,80],...
                      'String','●','FontSize',20,'Callback',...
                      'StickPicture(''Rec'')');                   
                   
%Slider_FrameNum
Slider_Ifr = uicontrol(gcf,'Style','Slider','Position',[500,90,280,20],...
                       'Min',Ifr,'Max',fr,'SliderStep',[1/fr 10/fr],'Value',Ifr,...
                       'Callback',['Ifr=round(get(Slider_Ifr,''Value''));',...
                       'set(Text_Ifr,''String'',num2str(Ifr));',...
                       'StickPicture(''SliderFN'')']);
%Text_FrameNum
Text_Ifr = uicontrol(gcf,'Style','Text','Position',[680,110,100,20],...
                     'String',num2str(get(Slider_Ifr,'Value')),'FontSize',10);

%Label_FrameNum
Label_Ifr = uicontrol(gcf,'Style','Text','Position',[500,110,180,20],...
                     'String','Frame Number : ','FontSize',10);
                   
%Slider_PlaybackSpeed
Slider_PBS = uicontrol(gcf,'Style','Slider','Position',[500,50,280,20],...
                       'Min',-1,'Max',1.5,'Value',PBS,...
                       'Callback',['PBS=get(Slider_PBS,''Value'');',...
                       'set(Text_PBS,''String'',num2str(PBS));',...
                       'StickPicture(''SliderPBS'');']);
                   
%Text_PlaybackSpeed
Text_PBS = uicontrol(gcf,'Style','Text','Position',[680,70,100,20],...
                       'String',num2str(get(Slider_PBS,'Value')),'FontSize',10);

%Laber_PlaybackSpeed
Label_PBS = uicontrol(gcf,'Style','Text','Position',[500,70,180,20],...
                       'String','Playback Speed : ','FontSize',10);                   
 
%Figure
ax = axes('Parent',gcf,'Position',[.15 .25 .7 .7]); 
axis([-2 2 -2 2 0 4]); view(az,el);
StickPicture('Pause');